{{- if eq .Values.deploymentType "Deployment"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels: {{- include "sonarqube.workloadLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels: {{- include "sonarqube.selectorLabels" . | nindent 6 }}
  {{- with .Values.deploymentStrategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "sonarqube.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: sonarqube
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: SONAR_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sonarqube-jdbc-secret
                  key: jdbc-username
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-jdbc-secret
                  key: jdbc-password
            - name: SONAR_JDBC_URL
              value: {{ .Values.jdbcOverwrite.jdbcUrl | quote }}
          # other configurations
{{- end }}

